project:
  type: website
  output-dir: docs

website:
  title: "Stepan Zaiatc"
  favicon: img/logo.png
  navbar:
    title: "**Stepan Zaiatc**"
    logo: img/logo.png
    logo-alt: "Stepan Zaiatc's Logo"
    right: 
      - href: index.qmd
        text: home 
      - href: projects.qmd
        text: projects
      - href: software.qmd
        text: software
      - href: cv.qmd
        text: cv
      - icon: linkedin
        href: https://www.linkedin.com/in/stepan-zaiatc/
      - icon: mastodon
        href: https://mastodon.social/@stepanData
      - icon: github
        href: https://github.com/stepanz25
      - icon: envelope
        href: mailto:zaiatc.stepan@gmail.com
  page-footer: 
    background: dark
    left: 
      - "Copyright &copy; 2023 by Stepan Zaiatc"
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/stepan-zaiatc/
      - icon: mastodon
        href: https://mastodon.social/@stepanData
      - icon: github # add icons that link to social media, etc.
        href: https://github.com/stepanz25
      - icon: envelope
        href: mailto:zaiatc.stepan@gmail.com

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, my_style.scss]
    mainfont: Jost
    css: styles.css